language: node_js
node_js:
  - node

cache: npm

script:
  - npm install codecov -g
  - ./bin/run --version
  - ./bin/run --help
  - npm run test


after_success:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - codecov
